services:
  postgres:
    image: postgres:17-bookworm

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # metabase:
  #   image: metabase/metabase:latest
  #
  #   ports:
  #     - "3000:3000"
  #
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #
  #   volumes:
  #     - metabase_data:/metabase-data

volumes:
  postgres_data:
  # metabase_data:
